import requests
import json

info = [
    {
        "id": "33791362",
        "name": "Luksuzni stan Regina u blizini centra",
        "cijena": "€50",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "242661779",
        "host_name": "Ivana",
        "host_rating": "4,9",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.51434",
        "longitude": "16.44862"
    },
    {
        "id": "2384574",
        "name": "Studio apartman za odmor u Hvaru A6",
        "cijena": "€32",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,76",
        "host_id": "2220540",
        "host_name": "Tonči",
        "host_rating": "4,76",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Hvar",
        "latitude": "43.1688",
        "longitude": "16.4448"
    },
    {
        "id": "589569775831149322",
        "name": "Predivna nova spavaća soba/u blizini plaže",
        "cijena": "€15",
        "broj_gostiju": 0,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 0,
        "rating": "Nema",
        "host_id": "18405854",
        "host_name": "Maria",
        "host_rating": "4,63",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50532",
        "longitude": "16.471"
    },
    {
        "id": "1121469158235272241",
        "name": "Apartman Seashell",
        "cijena": "€70",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "548945654",
        "host_name": "Petar",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Omiš",
        "latitude": "43.44167",
        "longitude": "16.69156"
    },
    {
        "id": "35869669",
        "name": "Jacuzzi apartman s pogledom na more Josipa",
        "cijena": "€71",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "269782681",
        "host_name": "Jozo",
        "host_rating": "4,86",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.50477",
        "longitude": "16.54334"
    },
    {
        "id": "37315135",
        "name": "Studio Lyra - u blizini plaže/centra",
        "cijena": "€35",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "280903351",
        "host_name": "Jakša",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5056",
        "longitude": "16.452"
    },
    {
        "id": "35967622",
        "name": "Apartment Carmen****, Žnjan, Split",
        "cijena": "€50",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "270550613",
        "host_name": "Karmen",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5035",
        "longitude": "16.4842"
    },
    {
        "id": "33989308",
        "name": "Studio Meje - uživajte na plaži Kaštelet (2 besplatna bicikla)",
        "cijena": "€30",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "256634518",
        "host_name": "Zdenka & Andrej",
        "host_rating": "4,84",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5043",
        "longitude": "16.4134"
    },
    {
        "id": "842061553403815890",
        "name": "Apartment Seaside",
        "cijena": "€99",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "504337546",
        "host_name": "Sara",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Jesenice",
        "latitude": "43.4646",
        "longitude": "16.5868"
    },
    {
        "id": "675159855771001843",
        "name": "Zvono br. 1",
        "cijena": "€28",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "5362997",
        "host_name": "Darko",
        "host_rating": "4,78",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50977",
        "longitude": "16.44389"
    },
    {
        "id": "6990578",
        "name": "Izravno na plaži+ kajak, SUP, ležaljke za sunčanje, parking",
        "cijena": "€57",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "26245581",
        "host_name": "Branka",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.4819",
        "longitude": "16.5566"
    },
    {
        "id": "1198546240126522043",
        "name": "Studio Apartman Ljuba",
        "cijena": "€41",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,92",
        "host_id": "529626810",
        "host_name": "Dora",
        "host_rating": "4,92",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5137",
        "longitude": "16.4377"
    },
    {
        "id": "17112149",
        "name": "Udoban stan s predivnim pogledom",
        "cijena": "€56",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "114925629",
        "host_name": "Jelena",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5035",
        "longitude": "16.4262"
    },
    {
        "id": "6690200",
        "name": "Apartman Marvin, Marjan Forest",
        "cijena": "€36",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "35016493",
        "host_name": "Stanislav",
        "host_rating": "4,9",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50792",
        "longitude": "16.42277"
    },
    {
        "id": "43685900",
        "name": "Infinity",
        "cijena": "€60",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "348904792",
        "host_name": "Marko",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Bilice",
        "latitude": "43.794",
        "longitude": "15.8971"
    },
    {
        "id": "1259953643091232039",
        "name": "Studio apartman Karla",
        "cijena": "€15",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "655412153",
        "host_name": "Karla",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Omiš",
        "latitude": "43.438966",
        "longitude": "16.698817"
    },
    {
        "id": "641779212695693923",
        "name": "La-Lu City i Beach Apartment",
        "cijena": "€50",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "213496422",
        "host_name": "Caroline",
        "host_rating": "4,96",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50634",
        "longitude": "16.46503"
    },
    {
        "id": "48198109",
        "name": "Hannin stan",
        "cijena": "€60",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "388810311",
        "host_name": "Marko",
        "host_rating": "4,96",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Okrug Gornji",
        "latitude": "43.48918",
        "longitude": "16.28039"
    },
    {
        "id": "1053468172572934485",
        "name": "Luksuzni apartman s jacuzzijem",
        "cijena": "€60",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "29503067",
        "host_name": "Anita",
        "host_rating": "4,83",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.48991",
        "longitude": "16.55014"
    },
    {
        "id": "18594169",
        "name": "Guest House Kala - Deluxe dvokrevetna soba",
        "cijena": "€30",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,87",
        "host_id": "82882782",
        "host_name": "Smoljo Family",
        "host_rating": "4,89",
        "županija": "Splitsko-Dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50908",
        "longitude": "16.43178"
    },
    {
        "id": "34381631",
        "name": "Panoramski apartman s pogledom na zalazak sunca",
        "cijena": "€38",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "186487612",
        "host_name": "Vedrana",
        "host_rating": "4,92",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.51403",
        "longitude": "16.44883"
    },
    {
        "id": "630340800095295283",
        "name": "Novi stan Cesarica s privatnim parkingom",
        "cijena": "€40",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "86640602",
        "host_name": "Goran",
        "host_rating": "4,98",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5159",
        "longitude": "16.4813"
    },
    {
        "id": "1086168369433477394",
        "name": "Udobna i simpatična spavaća soba, u blizini plaže\nBesplatan Netflix",
        "cijena": "€14",
        "broj_gostiju": 0,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 0,
        "rating": "Nema",
        "host_id": "18405854",
        "host_name": "Maria",
        "host_rating": "4,63",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50347",
        "longitude": "16.47312"
    },
    {
        "id": "16904176",
        "name": "AMFORA LUXURY STUDIO, OLD TOWN  4****",
        "cijena": "€50",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,92",
        "host_id": "14306976",
        "host_name": "Anita",
        "host_rating": "4,88",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.51092",
        "longitude": "16.43373"
    },
    {
        "id": "43766864",
        "name": "LUKSUZNI STUDIO ADENTE, 4*** CENTAR - STARI GRAD",
        "cijena": "€39",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "194256291",
        "host_name": "Frano",
        "host_rating": "4,94",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5079",
        "longitude": "16.43355"
    },
    {
        "id": "43929162",
        "name": "Apartman Emma - sve što vam je potrebno za uživanje",
        "cijena": "€66",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "351660008",
        "host_name": "Daliborka",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Trogir",
        "latitude": "43.52074",
        "longitude": "16.2505"
    },
    {
        "id": "23033518",
        "name": "Udoban stan u prizemlju",
        "cijena": "€28",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "29503067",
        "host_name": "Anita",
        "host_rating": "4,83",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.49109",
        "longitude": "16.54987"
    },
    {
        "id": "12321982",
        "name": "ARTEMIA",
        "cijena": "€29",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,91",
        "host_id": "66477216",
        "host_name": "Sanja",
        "host_rating": "4,92",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5086",
        "longitude": "16.4325"
    },
    {
        "id": "671538496107331469",
        "name": "Ljetni povjetarac 2",
        "cijena": "€27",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,89",
        "host_id": "5362997",
        "host_name": "Darko",
        "host_rating": "4,78",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50958",
        "longitude": "16.44215"
    },
    {
        "id": "16689085",
        "name": "Guest House Kala - Soba s pogledom na vrt",
        "cijena": "€30",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,9",
        "host_id": "82882782",
        "host_name": "Smoljo Family",
        "host_rating": "4,89",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50892",
        "longitude": "16.43175"
    },
    {
        "id": "14148784",
        "name": "Apartman s pogledom na Jadransko more A2 SPLIT,MARUŠIĆI,OMIŠ",
        "cijena": "€45",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,99",
        "host_id": "81604920",
        "host_name": "Sandra I Jurica",
        "host_rating": "4,95",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Marušići",
        "latitude": "43.4016",
        "longitude": "16.8291"
    },
    {
        "id": "18594779",
        "name": "Modern Home MARYN",
        "cijena": "€31",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "129109147",
        "host_name": "Ljiljana",
        "host_rating": "4,95",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5106",
        "longitude": "16.4557"
    },
    {
        "id": "32197176",
        "name": "Hrvatska Seaview",
        "cijena": "€55",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "241604026",
        "host_name": "Rene",
        "host_rating": "4,98",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podaca",
        "latitude": "43.1289",
        "longitude": "17.3434"
    },
    {
        "id": "35362170",
        "name": "Kuća Stina i vrt s veličanstvenim pogledom na more",
        "cijena": "€90",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "266225408",
        "host_name": "Marija",
        "host_rating": "4,88",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Sveta Nedilja",
        "latitude": "43.13381",
        "longitude": "16.59047"
    },
    {
        "id": "1047666029673928815",
        "name": "Villa Caverna",
        "cijena": "€86",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "127090393",
        "host_name": "Jana",
        "host_rating": "4,82",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Selca",
        "latitude": "43.2929",
        "longitude": "16.8486"
    },
    {
        "id": "1297926316629348056",
        "name": "Simpatična dvokrevetna kuća s grijanim bazenom",
        "cijena": "€110",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "Nema",
        "host_id": "663955636",
        "host_name": "Denis",
        "host_rating": "Nema ocjene",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.4903",
        "longitude": "16.5517"
    },
    {
        "id": "37324195",
        "name": "Lyra studio - s dva balkona",
        "cijena": "€35",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "280903351",
        "host_name": "Jakša",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5056",
        "longitude": "16.452"
    },
    {
        "id": "584766915654853000",
        "name": "Krasna soba/moderan stan./ Walk to Beach",
        "cijena": "€15",
        "broj_gostiju": 0,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 0,
        "rating": "Nema",
        "host_id": "18405854",
        "host_name": "Maria",
        "host_rating": "4,63",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.50372",
        "longitude": "16.47281"
    },
    {
        "id": "1155606084457808825",
        "name": "Apartman Amelia",
        "cijena": "€49",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "526002457",
        "host_name": "Lily",
        "host_rating": "5",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Kaštel Sućurac",
        "latitude": "43.5449",
        "longitude": "16.4265"
    },
    {
        "id": "1167548858071408664",
        "name": "Apartment MILLA,  \n Free Parking, Walk to do Beach",
        "cijena": "€50",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "580385849",
        "host_name": "Milan",
        "host_rating": "4,64",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.503592",
        "longitude": "16.45873"
    },
    {
        "id": "1135346338957203841",
        "name": "Stan - M&M Split",
        "cijena": "€29",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,93",
        "host_id": "572412605",
        "host_name": "Nataša",
        "host_rating": "4,87",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5088",
        "longitude": "16.4569"
    },
    {
        "id": "49088003",
        "name": "Old Stone House GP",
        "cijena": "€371",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "170703485",
        "host_name": "Petar And Nina",
        "host_rating": "4,96",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.4855",
        "longitude": "16.5793"
    },
    {
        "id": "36343117",
        "name": "Renovirani 2 BR Apartman 5 min do starog grada",
        "cijena": "€60",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 5,
        "broj_kupaonica": 1,
        "rating": "4,99",
        "host_id": "273302757",
        "host_name": "Petar",
        "host_rating": "4,99",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.511",
        "longitude": "16.4463"
    },
    {
        "id": "18592859",
        "name": "Moderni dom HUGO",
        "cijena": "€31",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "129109147",
        "host_name": "Ljiljana",
        "host_rating": "4,95",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5106",
        "longitude": "16.4557"
    },
    {
        "id": "16265897",
        "name": "NEVJEROJATNA KUĆA U ZALJEVU - DUGA",
        "cijena": "€89",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "27522248",
        "host_name": "Tonka",
        "host_rating": "4,82",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Okrug Gornji",
        "latitude": "43.4831",
        "longitude": "16.2424"
    },
    {
        "id": "1770657",
        "name": "Madonna 2",
        "cijena": "€35",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "9301219",
        "host_name": "Gordana",
        "host_rating": "4,87",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5095",
        "longitude": "16.4376"
    },
    {
        "id": "1063731113582987429",
        "name": "Stan na plaži",
        "cijena": "€85",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "555049918",
        "host_name": "Marja",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Jesenice",
        "latitude": "43.45485",
        "longitude": "16.62116"
    },
    {
        "id": "867189504108737399",
        "name": "Apartmani Vela Stiniva-2 Spavaća soba/Pogled na more/Terasa",
        "cijena": "€72",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "509536682",
        "host_name": "Tomislav",
        "host_rating": "4,94",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Jelsa",
        "latitude": "43.1558",
        "longitude": "16.8135"
    },
    {
        "id": "35345130",
        "name": "Studio apartman Vartal",
        "cijena": "€50",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "112097488",
        "host_name": "Benko",
        "host_rating": "4,96",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Jelsa",
        "latitude": "43.16306",
        "longitude": "16.70007"
    },
    {
        "id": "3588402",
        "name": "Little Seaside Paradise - dva bicikla",
        "cijena": "€90",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,99",
        "host_id": "18078825",
        "host_name": "Mirela",
        "host_rating": "4,99",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Rogačić",
        "latitude": "43.0781",
        "longitude": "16.1779"
    },
    {
        "id": "1070712150317990364",
        "name": "Studio apartman M",
        "cijena": "€12",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,9",
        "host_id": "422886558",
        "host_name": "Mate",
        "host_rating": "4,9",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Omiš",
        "latitude": "43.44",
        "longitude": "16.6996"
    },
    {
        "id": "23352758",
        "name": "Studio apartman s bazenom u centru Splita",
        "cijena": "€36",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,93",
        "host_id": "44023958",
        "host_name": "Elena",
        "host_rating": "4,92",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5076",
        "longitude": "16.4432"
    },
    {
        "id": "19636747",
        "name": "Guest House Maris  - luksuzna soba 4*",
        "cijena": "€30",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,89",
        "host_id": "137318218",
        "host_name": "Frano",
        "host_rating": "4,86",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Split",
        "latitude": "43.5083",
        "longitude": "16.4332"
    },
    {
        "id": "6611470",
        "name": "Izravno na plaži+kajak,SUP,ležaljke za sunčanje,parking",
        "cijena": "€53",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "26245581",
        "host_name": "Branka",
        "host_rating": "4,97",
        "županija": "Splitsko-dalmatinska županija",
        "grad": "Podstrana",
        "latitude": "43.4817",
        "longitude": "16.5566"
    },
    {
        "id": "1184687018824570953",
        "name": "Soba na selu u blizini Krka",
        "cijena": "€37",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "524608890",
        "host_name": "Nevio",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.059",
        "longitude": "14.5378"
    },
    {
        "id": "1162208649597900726",
        "name": "Villa Jelena",
        "cijena": "€285",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "Nema",
        "host_id": "578273833",
        "host_name": "Sabina",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Novi Vinodolski",
        "latitude": "45.138",
        "longitude": "14.7526"
    },
    {
        "id": "13253519",
        "name": "Corinne",
        "cijena": "€27",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,89",
        "host_id": "74560508",
        "host_name": "Sanjin",
        "host_rating": "4,91",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.1778",
        "longitude": "14.6913"
    },
    {
        "id": "19728912",
        "name": "Krk/ Blizu plaže / VEJA 2",
        "cijena": "€60",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "4,94",
        "host_id": "52677814",
        "host_name": "Dean",
        "host_rating": "4,84",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.0276",
        "longitude": "14.5859"
    },
    {
        "id": "3050936",
        "name": "Bijeli studio apartman",
        "cijena": "€29",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "7711345",
        "host_name": "Alen",
        "host_rating": "4,81",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.17337",
        "longitude": "14.69985"
    },
    {
        "id": "1180704698745208133",
        "name": "Kuća u uvali, uz samo more.",
        "cijena": "€300",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "583918435",
        "host_name": "Fran",
        "host_rating": "5",
        "županija": "Ličko-senjska županija",
        "grad": "Jablanac",
        "latitude": "44.7344",
        "longitude": "14.8982"
    },
    {
        "id": "46642264",
        "name": "Alpska kuća Klek",
        "cijena": "€71",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "376317388",
        "host_name": "Marko",
        "host_rating": "4,92",
        "županija": "Karlovačka županija",
        "grad": "Jasenak",
        "latitude": "45.256",
        "longitude": "15.01726"
    },
    {
        "id": "886680399335739817",
        "name": "Studio apartman \"Sivko\"",
        "cijena": "€75",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "76280081",
        "host_name": "Kristina",
        "host_rating": "4,92",
        "županija": "Primorsko-goranska županija",
        "grad": "Vrbnik",
        "latitude": "45.0757",
        "longitude": "14.6763"
    },
    {
        "id": "46774202",
        "name": "Alpska Kuća Lucy",
        "cijena": "€71",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "376317388",
        "host_name": "Marko",
        "host_rating": "4,92",
        "županija": "Karlovačka županija",
        "grad": "Jasenak",
        "latitude": "45.2552",
        "longitude": "15.01572"
    },
    {
        "id": "31523231",
        "name": "Studio Lavander  s privatnim vrtom",
        "cijena": "€45",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "236225697",
        "host_name": "Andrea",
        "host_rating": "4,96",
        "županija": "Primorsko-goranska županija",
        "grad": "Bakar",
        "latitude": "45.3066",
        "longitude": "14.5339"
    },
    {
        "id": "931888559796184064",
        "name": "Studio apartman Blu",
        "cijena": "€65",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "524680911",
        "host_name": "Magda",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Kornić",
        "latitude": "45.04838",
        "longitude": "14.61473"
    },
    {
        "id": "22348506",
        "name": "Udoban smještaj u Delnicama s kuhinjom",
        "cijena": "€39",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "4,78",
        "host_id": "141531977",
        "host_name": "Novasol",
        "host_rating": "4,39",
        "županija": "Primorsko-goranska županija",
        "grad": "Delnice",
        "latitude": "45.38",
        "longitude": "14.8342"
    },
    {
        "id": "23086134",
        "name": "Udoban obiteljski stan s 3 spavaće sobe Prebeg",
        "cijena": "€60",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "171438419",
        "host_name": "Zdravko",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Kornić",
        "latitude": "45.04346",
        "longitude": "14.61047"
    },
    {
        "id": "24215128",
        "name": "Novi stan u blizini lijepe plaže s pebbelom.",
        "cijena": "€59",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "182558765",
        "host_name": "Gordana",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Njivice",
        "latitude": "45.15374",
        "longitude": "14.53778"
    },
    {
        "id": "50169553",
        "name": "Kuća za odmor Lino",
        "cijena": "€153",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "4,95",
        "host_id": "404893411",
        "host_name": "Jadranka",
        "host_rating": "4,95",
        "županija": "Primorsko-goranska županija",
        "grad": "Donja Dobra",
        "latitude": "45.45562",
        "longitude": "14.97576"
    },
    {
        "id": "26520784",
        "name": "Apartman Ankica L4 (6 osoba)",
        "cijena": "€60",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "28817231",
        "host_name": "Igor",
        "host_rating": "4,9",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.1664",
        "longitude": "14.7073"
    },
    {
        "id": "20756563",
        "name": "★ NOVI stan Pogled na ★ more Centar★ grada★/ VEJA 1",
        "cijena": "€60",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,91",
        "host_id": "52677814",
        "host_name": "Dean",
        "host_rating": "4,84",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.0263",
        "longitude": "14.5712"
    },
    {
        "id": "28330148",
        "name": "Kamena kuća s pogledom na more",
        "cijena": "€60",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 5,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "213923357",
        "host_name": "Božidar",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Vrbnik",
        "latitude": "45.07727",
        "longitude": "14.67218"
    },
    {
        "id": "34264327",
        "name": "Sweet Apartment Katarina",
        "cijena": "€35",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,84",
        "host_id": "189707509",
        "host_name": "Kristina",
        "host_rating": "4,86",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.0281",
        "longitude": "14.5808"
    },
    {
        "id": "8271425",
        "name": "Studio Mari s privatnom terasom",
        "cijena": "€31",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "43614249",
        "host_name": "Mara",
        "host_rating": "4,93",
        "županija": "Primorsko-goranska županija",
        "grad": "Polje",
        "latitude": "45.13454",
        "longitude": "14.64629"
    },
    {
        "id": "1184687018824570953",
        "name": "Soba na selu u blizini Krka",
        "cijena": "€37",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "524608890",
        "host_name": "Nevio",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.059",
        "longitude": "14.5378"
    },
    {
        "id": "43878619",
        "name": "Mirna lokacija i blizina plaže i ostalog sadržaja",
        "cijena": "€55",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,93",
        "host_id": "351159618",
        "host_name": "Lana",
        "host_rating": "4,93",
        "županija": "Primorsko-goranska županija",
        "grad": "Baška",
        "latitude": "44.9703",
        "longitude": "14.7552"
    },
    {
        "id": "618002796147859715",
        "name": "Eko kuća Picik",
        "cijena": "€110",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,93",
        "host_id": "457111624",
        "host_name": "Marino",
        "host_rating": "4,93",
        "županija": "Primorsko-goranska županija",
        "grad": "Pinezići",
        "latitude": "45.0338",
        "longitude": "14.5109"
    },
    {
        "id": "13401243",
        "name": "Tradicionalna kamena kuća u Vrbniku, otok Krk",
        "cijena": "€79",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,91",
        "host_id": "76280081",
        "host_name": "Kristina",
        "host_rating": "4,92",
        "županija": "Primorsko-goranska županija",
        "grad": "Vrbnik",
        "latitude": "45.07705",
        "longitude": "14.67364"
    },
    {
        "id": "650738310901520454",
        "name": "KUĆA ZA ODMOR ADELAIDA 2",
        "cijena": "€100",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "4,91",
        "host_id": "116245525",
        "host_name": "Adeljajde",
        "host_rating": "4,88",
        "županija": "Primorsko-goranska županija",
        "grad": "Mali Lošinj",
        "latitude": "44.52549",
        "longitude": "14.48606"
    },
    {
        "id": "638774207176239091",
        "name": "Stan Maltar Lič",
        "cijena": "€58",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "408164634",
        "host_name": "Ante",
        "host_rating": "4,83",
        "županija": "Primorsko-goranska županija",
        "grad": "Lič",
        "latitude": "45.277",
        "longitude": "14.71731"
    },
    {
        "id": "932615276362153597",
        "name": "Udoban smještaj u selu na Krku",
        "cijena": "€40",
        "broj_gostiju": 0,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 0,
        "rating": "4,96",
        "host_id": "524608890",
        "host_name": "Nevio",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "krk Croatia ",
        "latitude": "45.0576",
        "longitude": "14.5352"
    },
    {
        "id": "37805005",
        "name": "Villa Festina Lente - udobna vila s grijanim bazenom",
        "cijena": "€140",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "4,89",
        "host_id": "161255915",
        "host_name": "Dejan",
        "host_rating": "4,89",
        "županija": "Primorsko-goranska županija",
        "grad": "Hlapa",
        "latitude": "45.13676",
        "longitude": "14.6223"
    },
    {
        "id": "50691544",
        "name": "Zarin smještaj s prekrasnim pogledom na more",
        "cijena": "€78",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,99",
        "host_id": "409635853",
        "host_name": "Goran",
        "host_rating": "4,99",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.17436",
        "longitude": "14.70428"
    },
    {
        "id": "1069666949624334494",
        "name": "Kuća Vista - Apartman 2",
        "cijena": "€80",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "556713273",
        "host_name": "Igor",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.1668",
        "longitude": "14.7102"
    },
    {
        "id": "22811482",
        "name": "Palm Springs",
        "cijena": "€55",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "167988427",
        "host_name": "Zoran",
        "host_rating": "4,93",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.03113",
        "longitude": "14.56643"
    },
    {
        "id": "1283443439722918283",
        "name": "Apartman Frajola",
        "cijena": "€70",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "282728356",
        "host_name": "Franka",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Fužine",
        "latitude": "45.3063",
        "longitude": "14.715"
    },
    {
        "id": "681228760265907782",
        "name": "Drveni planinski dom u zelenom srcu Hrvatske",
        "cijena": "€456",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "4,9",
        "host_id": "472087473",
        "host_name": "Vedrana",
        "host_rating": "4,9",
        "županija": "Primorsko-goranska županija",
        "grad": "Stari Laz",
        "latitude": "45.3612",
        "longitude": "14.8777"
    },
    {
        "id": "681847750766524798",
        "name": "Villa SPA - TERASA 3",
        "cijena": "€115",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "4,91",
        "host_id": "41407420",
        "host_name": "Tamara",
        "host_rating": "4,76",
        "županija": "Primorsko-goranska županija",
        "grad": "Dramalj",
        "latitude": "45.20468",
        "longitude": "14.66033"
    },
    {
        "id": "1158806062785925364",
        "name": "Kuća za odmor \"Dangubica\"",
        "cijena": "€105",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "551794111",
        "host_name": "Petar",
        "host_rating": "5",
        "županija": "Ličko-senjska županija",
        "grad": "Kuterevo",
        "latitude": "44.8277",
        "longitude": "15.138"
    },
    {
        "id": "54304244",
        "name": "Studio apartman Leo****",
        "cijena": "€55",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "440455655",
        "host_name": "Karmen",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.02336",
        "longitude": "14.5721"
    },
    {
        "id": "1056491138185321785",
        "name": "Planinska kuća LUIV Mrkopalj",
        "cijena": "€720",
        "broj_gostiju": 9,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 0,
        "broj_kupaonica": 4,
        "rating": "5,0",
        "host_id": "553110170",
        "host_name": "Sanja",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Mrkopalj",
        "latitude": "45.32479",
        "longitude": "14.86341"
    },
    {
        "id": "753302741112241446",
        "name": "Simpatično, ugodno, u blizini dvorca, smart TV, WI-FI, stari grad",
        "cijena": "€27",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,79",
        "host_id": "284546903",
        "host_name": "Barbara",
        "host_rating": "4,8",
        "županija": "Primorsko-goranska županija",
        "grad": "Bakar",
        "latitude": "45.30649",
        "longitude": "14.53439"
    },
    {
        "id": "673762279983175352",
        "name": "Landhaus Krk, lijep stan, mirna lokacija,Bask",
        "cijena": "€49",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 5,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "303421615",
        "host_name": "Manuela",
        "host_rating": "4,89",
        "županija": "Primorsko-goranska županija",
        "grad": "Baška",
        "latitude": "44.9711",
        "longitude": "14.7285"
    },
    {
        "id": "698982782233322190",
        "name": "apartment Hajsan",
        "cijena": "€100",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "154214257",
        "host_name": "Durdica",
        "host_rating": "5",
        "županija": "Ličko-senjska županija",
        "grad": "Senj",
        "latitude": "45.00084",
        "longitude": "14.89787"
    },
    {
        "id": "678309765688895095",
        "name": "Apartment Lynx on lake Sabljaci",
        "cijena": "€68",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 5,
        "broj_kupaonica": 1,
        "rating": "4,85",
        "host_id": "457891978",
        "host_name": "Stjepan",
        "host_rating": "4,85",
        "županija": "Karlovačka županija",
        "grad": "Sabljak Selo",
        "latitude": "45.2304",
        "longitude": "15.2208"
    },
    {
        "id": "44199902",
        "name": "Udoban studio",
        "cijena": "€41",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "355652572",
        "host_name": "Nadan",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Krk",
        "latitude": "45.0304",
        "longitude": "14.56645"
    },
    {
        "id": "40343362",
        "name": "Kuća za odmor Casa Kapusta",
        "cijena": "€255",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "311778098",
        "host_name": "Lorena",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Salopek Selo",
        "latitude": "45.2376",
        "longitude": "15.2151"
    },
    {
        "id": "853324697426023355",
        "name": "Apartman Jurić ,  prvi red do mora sa tri sobe",
        "cijena": "€130",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 4,
        "broj_kupaonica": 3,
        "rating": "5,0",
        "host_id": "506595920",
        "host_name": "Smiljana",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Klimno",
        "latitude": "45.15851",
        "longitude": "14.62241"
    },
    {
        "id": "38589764",
        "name": "Lič by Interhome",
        "cijena": "€188",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "4,88",
        "host_id": "123402172",
        "host_name": "Alen - Interhome Group",
        "host_rating": "4,69",
        "županija": "Primorsko-goranska županija",
        "grad": "Lič",
        "latitude": "45.274",
        "longitude": "14.7138"
    },
    {
        "id": "10585648",
        "name": "Miran stan s privatnim parkingom i terasom",
        "cijena": "€34",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "54610791",
        "host_name": "Dragana",
        "host_rating": "4,78",
        "županija": "Primorsko-goranska županija",
        "grad": "Rijeka",
        "latitude": "45.3431",
        "longitude": "14.4146"
    },
    {
        "id": "581466575573412480",
        "name": "Luvano's Place - kneževina Zarijak",
        "cijena": "€45",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "449309095",
        "host_name": "Radomir",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Punat",
        "latitude": "45.01101",
        "longitude": "14.62666"
    },
    {
        "id": "19704124",
        "name": "Apartmani „Nina” (6 osoba) - Mirno u blizini mora!",
        "cijena": "€60",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,9",
        "host_id": "135373670",
        "host_name": "Nina",
        "host_rating": "4,9",
        "županija": "Primorsko-goranska županija",
        "grad": "Pinezići",
        "latitude": "45.04396",
        "longitude": "14.48"
    },
    {
        "id": "18426839",
        "name": "Happy Beach Apartment 🤗 🏖🏡 - Dream on the Beach 💝",
        "cijena": "€100",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "127695676",
        "host_name": "Irena",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Kraljevica",
        "latitude": "45.2621",
        "longitude": "14.5684"
    },
    {
        "id": "44695082",
        "name": "Villa Anka",
        "cijena": "€190",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "231762065",
        "host_name": "Rok",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Sveti Ivan",
        "latitude": "45.0998",
        "longitude": "14.5273"
    },
    {
        "id": "45469274",
        "name": "Apartman Emili",
        "cijena": "€115",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "82095413",
        "host_name": "Perica",
        "host_rating": "5",
        "županija": "Primorsko-goranska županija",
        "grad": "Malinska",
        "latitude": "45.1171",
        "longitude": "14.5151"
    },
    {
        "id": "612133919188444729",
        "name": "Apartman Maria",
        "cijena": "€80",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "455749650",
        "host_name": "Maria",
        "host_rating": "4,91",
        "županija": "Ličko-senjska županija",
        "grad": "Sveta Jelena",
        "latitude": "45.01308",
        "longitude": "14.89273"
    },
    {
        "id": "33519541",
        "name": "Piramide Stare Mame na putu prema Risnjaku",
        "cijena": "€19",
        "broj_gostiju": 0,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 10,
        "broj_kupaonica": 1,
        "rating": "4,92",
        "host_id": "200753978",
        "host_name": "Bruna",
        "host_rating": "4,91",
        "županija": "Primorsko-goranska županija",
        "grad": "Lokve",
        "latitude": "45.3743",
        "longitude": "14.6589"
    },
    {
        "id": "19351576",
        "name": "Kuća za odmor Anita - otvorena tijekom cijele godine",
        "cijena": "€91",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "135608083",
        "host_name": "Denis",
        "host_rating": "4,97",
        "županija": "Primorsko-goranska županija",
        "grad": "Crikvenica",
        "latitude": "45.1742",
        "longitude": "14.7029"
    },
    {
        "id": "47724316",
        "name": "Villa Artemis",
        "cijena": "€165",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "4,96",
        "host_id": "275590040",
        "host_name": "Bojan",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Sveti Petar u Šumi",
        "latitude": "45.17833",
        "longitude": "13.86608"
    },
    {
        "id": "1016460914095185133",
        "name": "Udoban stan u Vrsaru s kuhinjom",
        "cijena": "€27",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "141551565",
        "host_name": "Novasol",
        "host_rating": "4,47",
        "županija": "Istarska županija",
        "grad": "Flengi",
        "latitude": "45.1644",
        "longitude": "13.6626"
    },
    {
        "id": "34834536",
        "name": "Studio apartman DEA u centru",
        "cijena": "€50",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,92",
        "host_id": "260510423",
        "host_name": "Danijela",
        "host_rating": "4,91",
        "županija": "Istarska županija",
        "grad": "Rovinj",
        "latitude": "45.0833",
        "longitude": "13.63317"
    },
    {
        "id": "51504766",
        "name": "Jabuke na prozoru Studio Bale",
        "cijena": "€46",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "408511253",
        "host_name": "Radana",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Bale",
        "latitude": "45.0413",
        "longitude": "13.7872"
    },
    {
        "id": "34734444",
        "name": "Apartment Danila, 4 + 1",
        "cijena": "€52",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "261958904",
        "host_name": "Stanko",
        "host_rating": "4,94",
        "županija": "Istarska županija",
        "grad": "Foli",
        "latitude": "45.0984",
        "longitude": "13.9181"
    },
    {
        "id": "35892051",
        "name": "Apartman za odmor VILLA BIANCA",
        "cijena": "€80",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "225200785",
        "host_name": "Davor",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Pazin",
        "latitude": "45.2255",
        "longitude": "13.95822"
    },
    {
        "id": "907325345098849506",
        "name": "Kuća za odmor MayaMarie (Grijani BAZEN od 01.04)",
        "cijena": "€110",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "518431379",
        "host_name": "Nenad",
        "host_rating": "4,98",
        "županija": "Istarska županija",
        "grad": "Bokordići",
        "latitude": "45.064",
        "longitude": "13.9106"
    },
    {
        "id": "29840371",
        "name": "Brijuni Loft s pogledom na more ****  •besplatan Netflix•",
        "cijena": "€33",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,98",
        "host_id": "15008291",
        "host_name": "Iva",
        "host_rating": "4,92",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.89476",
        "longitude": "13.81286"
    },
    {
        "id": "12885785",
        "name": "Obiteljski stan Niki",
        "cijena": "€60",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "70520317",
        "host_name": "Nevica",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Rovinj",
        "latitude": "45.0764",
        "longitude": "13.6544"
    },
    {
        "id": "1027545577097887626",
        "name": "Villa Martina, luksuzna novoizgrađena prizemnica",
        "cijena": "€115",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "547091248",
        "host_name": "Tamara",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Belavići",
        "latitude": "45.0002",
        "longitude": "14.002"
    },
    {
        "id": "44416312",
        "name": "Grijani bosses - Apartman Lux Villa Ren",
        "cijena": "€60",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "304245490",
        "host_name": "Elvis",
        "host_rating": "4,98",
        "županija": "Istarska županija",
        "grad": "Dajla",
        "latitude": "45.3511",
        "longitude": "13.5472"
    },
    {
        "id": "1181918354486631516",
        "name": "Villa Heureka - zadivljujući (grijani) bazen i sauna",
        "cijena": "Nema cijene",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 3,
        "rating": "Nema",
        "host_id": "584261290",
        "host_name": "Anđela",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Barat",
        "latitude": "45.1528",
        "longitude": "13.81851"
    },
    {
        "id": "49037012",
        "name": "CIJELA VILA NA OSAMI, UDALJENA 2 KM OD MORA!",
        "cijena": "€165",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 3,
        "broj_kreveta": 3,
        "broj_kupaonica": 3,
        "rating": "5,0",
        "host_id": "324538091",
        "host_name": "Romana",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Novigrad",
        "latitude": "45.3321",
        "longitude": "13.57949"
    },
    {
        "id": "43857784",
        "name": "Apartman EARTH🌎 (15km from Rovinj/from the sea)",
        "cijena": "€55",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "32988570",
        "host_name": "Family Meden",
        "host_rating": "4,83",
        "županija": "Istarska županija",
        "grad": "Kanfanar",
        "latitude": "45.12141",
        "longitude": "13.83895"
    },
    {
        "id": "1182373368368239976",
        "name": "San Rocco",
        "cijena": "€135",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "584387220",
        "host_name": "Helena",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Muntrilj",
        "latitude": "45.2426",
        "longitude": "13.807"
    },
    {
        "id": "1155802180523794515",
        "name": "Rabac SunTop apartment",
        "cijena": "€75",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "104470824",
        "host_name": "Tina",
        "host_rating": "4,91",
        "županija": "Istarska županija",
        "grad": "Rabac",
        "latitude": "45.0806",
        "longitude": "14.1551"
    },
    {
        "id": "35892051",
        "name": "Apartman za odmor VILLA BIANCA",
        "cijena": "€80",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "225200785",
        "host_name": "Davor",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Pazin",
        "latitude": "45.2255",
        "longitude": "13.95822"
    },
    {
        "id": "6586032",
        "name": "Stan na plaži",
        "cijena": "€50",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "34449735",
        "host_name": "Tea",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.8593",
        "longitude": "13.8235"
    },
    {
        "id": "44536434",
        "name": "Slikovita  istarska kuća u blizini Svetvincenata",
        "cijena": "€150",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "176974698",
        "host_name": "Maja",
        "host_rating": "4,79",
        "županija": "Istarska županija",
        "grad": "Svetvinčenat",
        "latitude": "45.09099",
        "longitude": "13.8443"
    },
    {
        "id": "1097225791396145585",
        "name": "Stan sa širokom terasom, miran i udoban",
        "cijena": "€70",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "332020217",
        "host_name": "Valentina",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Valbandon",
        "latitude": "44.91316",
        "longitude": "13.82849"
    },
    {
        "id": "34936945",
        "name": "Apartman Rožica",
        "cijena": "€42",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "263146558",
        "host_name": "Paolo",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Žminj",
        "latitude": "45.1371",
        "longitude": "13.8663"
    },
    {
        "id": "29183327",
        "name": "Casa Ava 2",
        "cijena": "€53",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "20771414",
        "host_name": "Danilo",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Štifanići",
        "latitude": "45.20212",
        "longitude": "13.75407"
    },
    {
        "id": "43858259",
        "name": "Apartman MOON🌙 (15 km udaljen/od mora)",
        "cijena": "€55",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "32988570",
        "host_name": "Family Meden",
        "host_rating": "4,83",
        "županija": "Istarska županija",
        "grad": "Kanfanar",
        "latitude": "45.12101",
        "longitude": "13.8384"
    },
    {
        "id": "6443651",
        "name": "Udoban i miran stan",
        "cijena": "€70",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "33642416",
        "host_name": "Lucano",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Medulin",
        "latitude": "44.82444",
        "longitude": "13.93426"
    },
    {
        "id": "896829968985929955",
        "name": "M&R studio beach and town",
        "cijena": "€29",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,94",
        "host_id": "4117231",
        "host_name": "Karolina",
        "host_rating": "4,94",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.85499",
        "longitude": "13.8383"
    },
    {
        "id": "1147759811950328266",
        "name": "Luksuzni apartman Niko",
        "cijena": "€53",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "575397234",
        "host_name": "Željko I Zorica",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Banjole",
        "latitude": "44.82093",
        "longitude": "13.8635"
    },
    {
        "id": "27524643",
        "name": "ZAZA Amphitheatre Studio apartman",
        "cijena": "€35",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,88",
        "host_id": "84045605",
        "host_name": "Dubravka",
        "host_rating": "4,91",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.8718",
        "longitude": "13.8526"
    },
    {
        "id": "16048314",
        "name": "Studio s velikim pogledom",
        "cijena": "€60",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,9",
        "host_id": "104470824",
        "host_name": "Tina",
        "host_rating": "4,91",
        "županija": "Istarska županija",
        "grad": "Rabac",
        "latitude": "45.0809",
        "longitude": "14.1583"
    },
    {
        "id": "831125853465137778",
        "name": "Villa Burra",
        "cijena": "€65",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "246350940",
        "host_name": "Ivan",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Peruški",
        "latitude": "44.94737",
        "longitude": "14.01612"
    },
    {
        "id": "50048060",
        "name": "Villa Karolina Ipši",
        "cijena": "€95",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "403675369",
        "host_name": "Elvis",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Ipši",
        "latitude": "45.3679",
        "longitude": "13.8494"
    },
    {
        "id": "35514341",
        "name": "Villa Luka",
        "cijena": "€140",
        "broj_gostiju": 8,
        "broj_spavacih_soba": 4,
        "broj_kreveta": 4,
        "broj_kupaonica": 4,
        "rating": "4,96",
        "host_id": "267185519",
        "host_name": "Branko",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Nova Vas",
        "latitude": "45.37823",
        "longitude": "13.64538"
    },
    {
        "id": "689782622391539629",
        "name": "Vrtna rezidencija Vila Goldimare - Suita Mare",
        "cijena": "€221",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "Nema",
        "host_id": "474141575",
        "host_name": "Zlata",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Umag",
        "latitude": "45.4047",
        "longitude": "13.5305"
    },
    {
        "id": "22409663",
        "name": "vila s jagodama",
        "cijena": "€38",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "152622218",
        "host_name": "Goran",
        "host_rating": "4,92",
        "županija": "Istarska županija",
        "grad": "Motovun",
        "latitude": "45.33543",
        "longitude": "13.82825"
    },
    {
        "id": "668845909796339616",
        "name": "Villa Aquila s bazenom",
        "cijena": "€140",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "2535931",
        "host_name": "Andreja",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Sveti Petar u Šumi",
        "latitude": "45.17812",
        "longitude": "13.86512"
    },
    {
        "id": "8481614",
        "name": "Prekrasan pogled na more",
        "cijena": "€40",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 1,
        "rating": "4,82",
        "host_id": "28003487",
        "host_name": "Željko",
        "host_rating": "4,57",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.89479",
        "longitude": "13.81199"
    },
    {
        "id": "739084966203111335",
        "name": "Cool Stay @ Port - prvi red do mora!",
        "cijena": "€75",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,93",
        "host_id": "29989230",
        "host_name": "Deni",
        "host_rating": "4,88",
        "županija": "Istarska županija",
        "grad": "Plomin Luka",
        "latitude": "45.1343",
        "longitude": "14.1762"
    },
    {
        "id": "13691379",
        "name": "Villa Paradiso Stara tradicionalna istarska kuća",
        "cijena": "€159",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "4,95",
        "host_id": "79785959",
        "host_name": "Stefan",
        "host_rating": "4,94",
        "županija": "Istarska županija",
        "grad": "Umag",
        "latitude": "45.42451",
        "longitude": "13.60251"
    },
    {
        "id": "17419114",
        "name": "Apartment Marija",
        "cijena": "€27",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "117808918",
        "host_name": "Marija Ermida",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Barban",
        "latitude": "45.06523",
        "longitude": "14.0108"
    },
    {
        "id": "851557977557356035",
        "name": "Villa Hedonia",
        "cijena": "€100",
        "broj_gostiju": 5,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 2,
        "rating": "Nema",
        "host_id": "506315446",
        "host_name": "Hana",
        "host_rating": "4,86",
        "županija": "Istarska županija",
        "grad": "Mugeba",
        "latitude": "45.209",
        "longitude": "13.6127"
    },
    {
        "id": "37032053",
        "name": "Moderan studio apartman u središnjoj Istri",
        "cijena": "€55",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,99",
        "host_id": "278437279",
        "host_name": "Antonio",
        "host_rating": "4,99",
        "županija": "Istarska županija",
        "grad": "Gračišće",
        "latitude": "45.21206",
        "longitude": "14.02449"
    },
    {
        "id": "642435876609724042",
        "name": "Kuća za odmor s 1 spavaćom sobom i besplatnim parkingom",
        "cijena": "€65",
        "broj_gostiju": 3,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,81",
        "host_id": "462635939",
        "host_name": "Roland",
        "host_rating": "4,84",
        "županija": "Istarska županija",
        "grad": "Rovinj",
        "latitude": "45.0639",
        "longitude": "13.6889"
    },
    {
        "id": "41171450",
        "name": "Studio za dvije/ 2 min do plaže/ Pogled na more i balkon",
        "cijena": "€40",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "44743085",
        "host_name": "Andrea",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.8559",
        "longitude": "13.8325"
    },
    {
        "id": "678185473394172100",
        "name": "Apartman St. Valkanela",
        "cijena": "€70",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "30919081",
        "host_name": "Domeniko",
        "host_rating": "4,96",
        "županija": "Istarska županija",
        "grad": "Vrsar",
        "latitude": "45.1618",
        "longitude": "13.6098"
    },
    {
        "id": "620906234446732266",
        "name": "Simpatičan studio iznad šetnice s terasom i parkingom",
        "cijena": "€70",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "174797760",
        "host_name": "Samanta",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Rabac",
        "latitude": "45.0784",
        "longitude": "14.1568"
    },
    {
        "id": "1153565550947879494",
        "name": "Srce Istre - Stan - Pazin",
        "cijena": "€76",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 4,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "576831709",
        "host_name": "Tonči",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Bertoši",
        "latitude": "45.2237",
        "longitude": "13.9163"
    },
    {
        "id": "1202691000676832849",
        "name": "BABO 2 Bedroom Apartment & Balcony H",
        "cijena": "€35",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "365249167",
        "host_name": "Barbara & Boško",
        "host_rating": "4,99",
        "županija": "Istarska županija",
        "grad": "Rovinj",
        "latitude": "45.08821",
        "longitude": "13.64925"
    },
    {
        "id": "43857784",
        "name": "Apartman EARTH🌎 (15km from Rovinj/from the sea)",
        "cijena": "€55",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "Nema",
        "host_id": "32988570",
        "host_name": "Family Meden",
        "host_rating": "4,83",
        "županija": "Istarska županija",
        "grad": "Kanfanar",
        "latitude": "45.12141",
        "longitude": "13.83895"
    },
    {
        "id": "880879800159785029",
        "name": "Studio apartman Mare s jacuzzijem",
        "cijena": "€49",
        "broj_gostiju": 2,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "4,95",
        "host_id": "512426979",
        "host_name": "Marija",
        "host_rating": "4,95",
        "županija": "Istarska županija",
        "grad": "Vinkuran",
        "latitude": "44.8351",
        "longitude": "13.8631"
    },
    {
        "id": "928924667362930069",
        "name": "Casa Stella",
        "cijena": "€57",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 2,
        "rating": "5,0",
        "host_id": "174916661",
        "host_name": "Marina",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Draguć",
        "latitude": "45.3322",
        "longitude": "14.0037"
    },
    {
        "id": "7233066",
        "name": "App Sea, 70 m od plaže",
        "cijena": "€50",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,96",
        "host_id": "37858222",
        "host_name": "Sara",
        "host_rating": "4,98",
        "županija": "Istarska županija",
        "grad": "Pula",
        "latitude": "44.8591",
        "longitude": "13.8237"
    },
    {
        "id": "673098097503011335",
        "name": "Kuća Kova - omaž ugljenom",
        "cijena": "€95",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 3,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "469988945",
        "host_name": "Biljana",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Labin",
        "latitude": "45.10363",
        "longitude": "14.12225"
    },
    {
        "id": "3268869",
        "name": "Nadijina kuća, idila u središtu Istre",
        "cijena": "€70",
        "broj_gostiju": 6,
        "broj_spavacih_soba": 2,
        "broj_kreveta": 5,
        "broj_kupaonica": 1,
        "rating": "4,97",
        "host_id": "16529245",
        "host_name": "Nadia",
        "host_rating": "4,97",
        "županija": "Istarska županija",
        "grad": "Pićan",
        "latitude": "45.20356",
        "longitude": "14.04157"
    },
    {
        "id": "20930710",
        "name": "Romantična vila s bazenom u blizini mora",
        "cijena": "€126",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 1,
        "broj_kupaonica": 1,
        "rating": "5,0",
        "host_id": "150168593",
        "host_name": "Ana",
        "host_rating": "5",
        "županija": "Istarska županija",
        "grad": "Peroj",
        "latitude": "44.9455",
        "longitude": "13.7924"
    },
    {
        "id": "29580635",
        "name": "Moderan stan u istarskoj kamenoj kući",
        "cijena": "€43",
        "broj_gostiju": 4,
        "broj_spavacih_soba": 0,
        "broj_kreveta": 2,
        "broj_kupaonica": 1,
        "rating": "4,85",
        "host_id": "6223334",
        "host_name": "Samanta",
        "host_rating": "4,7",
        "županija": "Istarska županija",
        "grad": "Tar",
        "latitude": "45.30188",
        "longitude": "13.62394"
    }
]

import requests
import re

def get_municipality_or_town(lat, lon):
    url = "https://nominatim.openstreetmap.org/reverse"
    params = {
        "lat": lat,
        "lon": lon,
        "format": "json",
        "addressdetails": 1
    }
    headers = {
        "User-Agent": "Script/1.0 (juricacizic@gmail.com)"
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()

        address = data.get("address", {})
        municipality = address.get("municipality")
        town = address.get("town")

        if municipality:
            return municipality.replace("Općina ", "").replace("Grad ", "").strip()
        elif town:
            return town.replace("Grad ", "").strip()
        else:
            display_name = data.get("display_name", "")
            
            match = re.search(r'Općina\s+([^,]+)', display_name)
            if match:
                return match.group(1).strip()
            match = re.search(r'Grad\s+([^,]+)', display_name)
            if match:
                return match.group(1).strip()
            return 0
    except requests.RequestException as e:
        return f"Error: {e}"

    
def get_detailed_info(lat, lon):
    url = "https://nominatim.openstreetmap.org/reverse"
    params = {
        "lat": lat,
        "lon": lon,
        "format": "json",
        "addressdetails": 1
    }
    headers = {
        "User-Agent": "Script/1.0 (juricacizic@gmail.com)"
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()

        return data
    except requests.RequestException as e:
        return f"Error: {e}"

for listing in info:
    trenutniGrad = listing["grad"]
    opcina = get_municipality_or_town(listing["latitude"], listing["longitude"])
    listing["praviGrad"] = trenutniGrad
    if opcina != 0:
        listing["grad"] = opcina
    else:
        listing["grad"] = "Nije pronađeno ime općine"
    print(listing, "\n\n")

with open("listingsDetails.json", "w", encoding="utf-8") as f:
    json.dump(info, f, ensure_ascii=False, indent=4)

print("Data saved to listingsDetails.json")